### PR TITLE
Case insensitive MultiPolygon

### PR DESCRIPTION
**Pull request by waissbluth**
Supporting both "Multipolygon" and "MultiPolygon" as type name.

### CODE REVIEW

**Comment by andrewharvey** [comment]
:+1: 

https://tools.ietf.org/html/rfc7946#section-1.4

>  Inside this document, the term "geometry type" refers to seven
>      **case-sensitive** strings: "Point", "MultiPoint", "LineString",
>      "MultiLineString", "Polygon", "MultiPolygon", and
>      "GeometryCollection".

I'd go further and replace instead of extend.

**Comment by andrewharvey** [comment]
@tyrasd did you have a chance to review this?

**Comment by Beakerboy** [comment]
Any word on if this will ever be merged?

**Comment by tyrasd** [comment]
This is now available as v0.0.4. Sorry for not taking care of this earlier. :bow:

**Pull request merged**
